---
title: "R Notebook"
output: html_notebook
---

```{r, message = FALSE}
library(factoextra)
library(FactoMineR)
library(readxl)
library(reshape2)
library(pheatmap)
library(RColorBrewer)
```


On extrait les valeurs numériques et les facteurs
```{r}
load("data/exposome.RData")
codebook = as.data.frame(read_xlsx("data/codebook.xlsx"))
exposome_num = exposome[ , codebook$variable_name[1:222][which(codebook$var_type[1:222] == "numeric")]]
exposome_fac = exposome[ , codebook$variable_name[1:222][which(codebook$var_type[1:222] == "factor")]]
```

<!-- On isole les valeurs prénatales et les valeurs post-natales -->
<!-- ```{r} -->
<!-- X_num_preg = exposome_num[ , codebook$variable_name[1:222][which(codebook$period[1:222] == "Pregnancy" & codebook$var_type[1:222] == "numeric")]] -->
<!-- X_num_post = exposome_num[ , codebook$variable_name[1:222][which(codebook$period[1:222] != "Pregnancy" & codebook$var_type[1:222] == "numeric")]] -->
<!-- ``` -->

```{r}
df = data.frame(exposome_num, 
                cohort = covariates$h_cohort,
                phenotype[, -1])

fit_num = prcomp(exposome_num, scale = TRUE)
```


```{r}
pvalues_mat <- matrix( , nrow=dim(exposome_num)[2], ncol=2)

j = 1
for (expo in colnames(exposome_num)) {
  glm = glm(phenotype[, "hs_correct_raven"] ~ cohort + exposome_num[, expo], family = gaussian, data = df)
  pvalues_mat[j, 1] <- tail(summary(glm)$coefficient, n=1)[4]
  j = j + 1
}

j = 1
for (expo in colnames(exposome_num)) {
  glm = glm(phenotype[, "hs_Gen_Tot"] ~ cohort + exposome_num[, expo], family = gaussian, data = df)
  pvalues_mat[j, 2] <- tail(summary(glm)$coefficient, n=1)[4]
  j = j + 1
}

colnames(pvalues_mat) <- c("hs_correct_raven", "hs_Gen_Tot")
rownames(pvalues_mat) <- colnames(exposome_num)

```


On utilise ensuite une heatmap pour représenter l'effet des exposomes sur les phénotypes.
```{r}

mat_row = data.frame(family = codebook$family[1:222][which(codebook$variable_name[1:222] %in% rownames(pvalues_mat))])
rownames(mat_row) <- rownames(pvalues_mat)

mat_colors <- list(family = colorRampPalette(brewer.pal(8, "Set2"))(length(unique(codebook$family[1:222]))))
names(mat_colors$family) <- unique(codebook$family[1:222])

# pvalues_melt <- melt(pvalues_preg)
# pvalues_melt$expo <- rep(rownames(pvalues_preg), 5)

pheatmap(
  mat = pvalues_mat,
  color = colorRampPalette(c("#000091", "white", "#E1000F"))(50),
  annotation_row = mat_row,
  annotation_colors = mat_colors,
  cluster_rows = FALSE,
  cluster_cols = FALSE,
  fontsize          = 10,
  main              = "Exposomes' correlation to phenotypes"
)

# ggplot(pvalues_melt, aes(x = variable, y = expo)) + 
# geom_tile(aes(fill = value), colour = "white") +
# scale_fill_gradient(low = "blue", high = "white") +
# scale_x_discrete(guide = guide_axis(angle = 90))
```


On essaie cette fois de repérer les p-values inférieures à 0,05

```{r}

neg_log_p_values = -log10(pvalues_mat)
threshold <- -log10(0.05)
annotations <- as.data.frame(ifelse(neg_log_p_values >= threshold, "Significant", "Non-Significant"))
rownames(annotations) <- rownames(neg_log_p_values)
colnames(annotations) <- colnames(neg_log_p_values)

pheatmap(
  mat = neg_log_p_values,
  cluster_rows = FALSE,
  cluster_cols = FALSE,
  annotation_row = annotations,
  fontsize          = 5,
  main              = "Exposomes' correlation to phenotypes"
)

significant_values = as.data.frame(annotations[annotations$hs_Gen_Tot == "Significant", "hs_Gen_Tot"])
rownames(significant_values) <- rownames(annotations[annotations$hs_Gen_Tot == "Significant", ])
colnames(significant_values) <- "hs_Gen_tot"

```


